// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Update201911121451 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update201911121451));
        
        string IMigrationMetadata.Id
        {
            get { return "201906230145536_Update201911121451"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
